services:
  app:
    depends_on:
      - db
    image: lawitz/myapp:latest
    restart: unless-stopped
    env_file:
      - ./../.env
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    env_file:
      - ./../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: