name: test

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: log into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          file: ./dep2/Dockerfile
          tags: |
            ${{secrets.DOCKER_USERNAME}}/myapp:${{github.sha}}
            ${{secrets.DOCKER_USERNAME}}/myapp:latest
          push: true